import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import test from "node:test";

const script = fileURLToPath(new URL("./check-generated-markers.mjs", import.meta.url));
const shippedFolder = fileURLToPath(new URL(".", import.meta.url));

function runCheck(root) {
  return spawnSync(process.execPath, [script, "--root", root], { encoding: "utf8" });
}

async function createFixture(manifest) {
  const root = await mkdtemp(join(tmpdir(), "generated-markers-"));
  await writeFile(join(root, "generated-manifest.json"), `${JSON.stringify(manifest, null, 2)}\n`);
  return root;
}

test("the shipped folder passes: its one generated file is listed", () => {
  const result = runCheck(shippedFolder);
  assert.equal(result.status, 0, result.stderr);
  assert.match(result.stdout, /complete \(1 file\(s\) listed\)/);
});

test("a marked file missing from the manifest fails", async () => {
  const root = await createFixture({ generated: [] });
  try {
    await writeFile(
      join(root, "derived.mjs"),
      ["/* @generated by fixture-tool */", "export const value = 1;", ""].join("\n"),
    );
    const result = runCheck(root);
    assert.equal(result.status, 1);
    assert.match(result.stderr, /Generated file is not listed .*derived\.mjs/);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("a listed file that no longer exists fails", async () => {
  const root = await createFixture({ generated: ["generated/removed.json"] });
  try {
    const result = runCheck(root);
    assert.equal(result.status, 1);
    assert.match(result.stderr, /Listed generated file is missing: generated\/removed\.json/);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("a listed and present marked file passes, wherever it lives", async () => {
  const root = await createFixture({ generated: ["nested/derived.md"] });
  try {
    await mkdir(join(root, "nested"));
    await writeFile(
      join(root, "nested", "derived.md"),
      ["<!-- @generated by fixture-tool -->", "", "# Derived", ""].join("\n"),
    );
    const result = runCheck(root);
    assert.equal(result.status, 0, result.stderr);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("marked files inside node_modules are not swept", async () => {
  const root = await createFixture({ generated: [] });
  try {
    await mkdir(join(root, "node_modules"));
    await writeFile(
      join(root, "node_modules", "vendored.mjs"),
      ["// @generated upstream", "export {};", ""].join("\n"),
    );
    const result = runCheck(root);
    assert.equal(result.status, 0, result.stderr);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("duplicate manifest entries fail", async () => {
  const root = await createFixture({ generated: ["a.json", "a.json"] });
  try {
    await writeFile(join(root, "a.json"), "{}\n");
    const result = runCheck(root);
    assert.equal(result.status, 1);
    assert.match(result.stderr, /duplicate entry a\.json/);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});
